### ISSUE TITLE
Exported SLPK (I3SEncoder) cannot be read by ArcGIS Pro

### ISSUE THREAD

**Issue by giserHacter** [Esri/pyprt#46] opened 2020-06-23 09:35 UTC
Hello,devops

I have tested pypty I3SEncoder and find a question,here are some detail:
1、SLPK was successfully generated(obj->slpk) and my test code is:

```
import os
import pyprt

CS_FOLDER = os.path.dirname(os.path.realpath(__file__))


def asset_file(filename):
    return os.path.join(os.path.dirname(CS_FOLDER),"MergeLod","models", filename)


def asset_output_file(filename):
    return os.path.join(os.path.dirname(CS_FOLDER), 'export', filename)


pyprt.initialize_prt()
if os.path.isfile(asset_output_file('Unittest4SLPK.slpk')):
    os.remove(asset_output_file('Unittest4SLPK.slpk'))

encoder_options = {
    'outputPath': os.path.dirname(asset_output_file(''))}
os.makedirs(encoder_options['outputPath'], exist_ok=True)

shape_geo_from_obj = pyprt.InitialShape(
    asset_file("myCity_0.obj"))
rpk = r"D:\TEST\cpp\MergeLod\MergeLod\test.rpk"
attrs = {'ruleFile': 'bin/test.cgb', 'startRule': 'Default$Lot',
        }
slpk_options = {'layerTextureEncoding': ['2'], 'layerEnabled': [True], 'layerUID': ['1'],
                'layerName': ['Salut'], 'layerTextureQuality': [1.0], 'layerTextureCompression': [9],
                'layerTextureScaling': [1.0], 'layerTextureMaxDimension': [2048],
                'layerFeatureGranularity': ['0'], 'layerBackfaceCulling': [False], 'baseName': 'Unittest4SLPK'}
slpk_options.update(encoder_options)
m = pyprt.ModelGenerator([shape_geo_from_obj])
m.generate_model(
    [attrs], rpk, 'com.esri.prt.codecs.I3SEncoder', slpk_options)
pyprt.shutdown_prt()
```
2、The slpk is miss in arcgis pro,and i find the inner data structure of slpk is incorrect

test data download address:
https://1drv.ms/u/s!ArMagmiusEb0hk0koJ4Rk9CHZYL4?e=IeqUez

**Comment by mistafunk** [comment] 2020-06-24 07:01
Thanks for your bug report, we'll take a look at the SLPK.

**Comment by mistafunk** [comment] 2020-06-24 07:10
@giserHacter The link you provided did not contain a SLKP, did you link the wrong data?

**Comment by mistafunk** [comment] 2020-07-20 06:33
Closing this due to missing reproduction data/details. Please reopen if there is new data.

**Closed by mistafunk** 2020-07-20 06:33 UTC
Labels: bug
